language: android
dist: trusty
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-30"
android:
    components:
    - build-tools-30.0.3
    - android-30
    
env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8
    
# Emulator Management: Create, Start and Wait
before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-30 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew connectedAndroidTest