/*
 * MobileMovieBase
 * This is the MobileMovieBase server.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hargitomi97@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.mobilemoviebase.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

/**
 * MovieWithDetailsRatings
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-23T14:07:28.797Z[GMT]")
public class MovieWithDetailsRatings {
  @SerializedName("Source")
  private String source = null;

  @SerializedName("Value")
  private String value = null;

  public MovieWithDetailsRatings source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public MovieWithDetailsRatings value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MovieWithDetailsRatings movieWithDetailsRatings = (MovieWithDetailsRatings) o;
    return Objects.equals(this.source, movieWithDetailsRatings.source) &&
        Objects.equals(this.value, movieWithDetailsRatings.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(source, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MovieWithDetailsRatings {\n");
    
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
