/*
 * MobileMovieBase
 * This is the MobileMovieBase server.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hargitomi97@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.mobilemoviebase.model;

import com.example.mobilemoviebase.network.OneOfinlineResponse200;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Movie
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-04-23T14:07:28.797Z[GMT]")
public class MovieResult implements OneOfinlineResponse200 {
  @SerializedName("Search")
  private List<Movie> search = null;

  @SerializedName("totalResults")
  private Integer totalResults = null;

  @SerializedName("Response")
  private Boolean response = null;

  public MovieResult(List<Movie> search, Integer totalResults, Boolean response) {
    this.search = search;
    this.totalResults = totalResults;
    this.response = response;
  }

  public MovieResult search(List<Movie> search) {
    this.search = search;
    return this;
  }

  public MovieResult addSearchItem(Movie searchItem) {
    if (this.search == null) {
      this.search = new ArrayList<Movie>();
    }
    this.search.add(searchItem);
    return this;
  }

   /**
   * Get search
   * @return search
  **/
  public List<Movie> getSearch() {
    return search;
  }

  public void setSearch(List<Movie> search) {
    this.search = search;
  }

  public MovieResult totalResults(Integer totalResults) {
    this.totalResults = totalResults;
    return this;
  }

   /**
   * Get totalResults
   * @return totalResults
  **/
  public Integer getTotalResults() {
    return totalResults;
  }

  public void setTotalResults(Integer totalResults) {
    this.totalResults = totalResults;
  }

  public MovieResult response(Boolean response) {
    this.response = response;
    return this;
  }

   /**
   * Get response
   * @return response
  **/
  public Boolean isResponse() {
    return response;
  }

  public void setResponse(Boolean response) {
    this.response = response;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MovieResult movieRepository = (MovieResult) o;
    return Objects.equals(this.search, movieRepository.search) &&
        Objects.equals(this.totalResults, movieRepository.totalResults) &&
        Objects.equals(this.response, movieRepository.response);
  }

  @Override
  public int hashCode() {
    return Objects.hash(search, totalResults, response);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Movie {\n");
    
    sb.append("    search: ").append(toIndentedString(search)).append("\n");
    sb.append("    totalResults: ").append(toIndentedString(totalResults)).append("\n");
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
